### PR TITLE
Https and multi project fixes

### PR DESCRIPTION
**Pull request by alpar-t**
I recently used this plugin for some work and found these problems.
I initially worked around them, now I took the time to back-port the workarounds as proper fixes.

### CODE REVIEW

**Comment by thokari** [comment]
Thanks, much appreciated!

**Comment by atorok** [comment]
Any chance you could do a release that includes these ? Thanks !

**Comment by thokari** [comment]
I did it right away, here you go: https://bintray.com/thokari/maven/gradle-geb-plugin/0.4/view

**Comment by atorok** [comment]
Thanks! I just noticed, Readme.md still has 3.0

Alpar Torok

**Pull request closed without merging**
